name: CD with Docker

on:
  workflow_run:
    workflows: [ "Java CI & Docker Build" ]  # CI 워크플로우 이름과 정확히 일치
    types: [ completed ]
    branches: [ "dev" ]

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    # ① Repository Variables로 설정한 값들을 env로 끌어오기
    env:
      CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
      NETWORK_NAME:   ${{ vars.NETWORK_NAME }}
      DEV_WEB_PORT:   ${{ vars.DEV_WEB_PORT }}

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Pull Docker image (short SHA)
        run: |
          FULL_SHA=${{ github.event.workflow_run.head_sha }}
          SHORT_SHA=${FULL_SHA:0:7}  
          IMAGE=ghcr.io/likelion-avengers/backend:sha-${SHORT_SHA}
          echo "Pulling $IMAGE"
          docker pull "$IMAGE"

      - name: Remove old container
        run: docker rm -f "$CONTAINER_NAME" || true

      - name: Prune old images
        run: |
          docker images "ghcr.io/likelion-avengers/backend" \
            --format "{{.Repository}}:{{.Tag}}" \
            | grep -v "sha-${SHORT_SHA}" \
            | xargs -r docker rmi -f || true

      - name: Run new container
        run: |
          IMAGE=ghcr.io/likelion-avengers/backend:sha-${SHORT_SHA}
          docker run -d \
            --name "$CONTAINER_NAME" \
            --network "$NETWORK_NAME" \
            -p "${DEV_WEB_PORT}:8080" \
            -e USE_PROFILE=dev \
            -e TZ=Asia/Seoul \
            "$IMAGE"
