name: Java CI & Docker Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스+서브모듈 체크아웃 (PAT로 인증)
      - name: Checkout source & submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}

      # 2) JDK 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3) Gradle 빌드 (Fat JAR 생성)
      - name: Build with Gradle
        run: ./gradlew clean bootJar --no-daemon

      # 4) Docker Buildx 준비
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5) GHCR 로그인 (PAT 사용)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      # 6) 메타데이터 추출 (태그 SHA)
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha

      # 7) Docker 이미지 빌드 & 푸시 (PAT로 권한)
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
