name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  checks: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스 코드 + 서브모듈 체크아웃 (PAT 사용)
      - name: Checkout source & submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}

      # 2) gradlew 실행 권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      # 3) JDK 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 4) Gradle 캐싱 및 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 5) 실제 빌드 수행 (Fat JAR 생성)
      - name: Build with Gradle
        run: ./gradlew clean bootJar --no-daemon

      # 6) 테스트 결과 리포트
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      # 7) 빌드 산출물 업로드 (JAR, Dockerfile, module 서브모듈)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-libs
          path: |
            build/libs/*.jar
            Dockerfile
            module/**
