name: CD with Docker


on:
  workflow_run:
    workflows: [ "Java CI WITH Gradle" ]
    types: [ completed ]
    branches: [ "dev" ]

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      # 1) GHCR 로그인 (PAT 사용)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      # 2) 최신 이미지 Pull (SHA 태그)
      - name: Pull Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.head_sha }}
          docker pull $IMAGE

      # 3) 기존 컨테이너 종료
      - name: Remove old container
        run: docker rm -f ${{ vars.CONTAINER_NAME }} || true

      # 4) 오래된 이미지 정리
      - name: Prune old images
        run: |
          docker images "ghcr.io/${{ github.repository }}" \
            --format "{{.Repository}}:{{.Tag}}" \
            | grep -v "${{ github.event.workflow_run.head_sha }}" \
            | xargs -r docker rmi -f || true

      # 5) 새 컨테이너 실행
      - name: Run new container
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.head_sha }}
          docker run -d \
            --name ${{ vars.CONTAINER_NAME }} \
            --network ${{ vars.NETWORK_NAME }} \
            -p ${{ secrets.DEV_WEB_PORT }}:8080 \
            -e USE_PROFILE=dev \
            -e TZ=Asia/Seoul \
            $IMAGE
